### ISSUE TITLE
Make entities __eq__ comparable

### ISSUE THREAD

**Issue by rochacbruno** [SatelliteQE/nailgun#335]
As soon as #326 got merged, having proper json generation we should implement the `__eq__` method in `Entity` mixin making entities fully comparable by equality of its fields.

Example:

```python
>>> Host(id=1) == Host(id=1)
True
```

The `__eq__` should serialize the entity to JSON, ensure it is `read` again from server and then compare all fields and values, only if all `_fields` has same values it should return True.

That helps with unit tests

**Comment by omaciel** [comment]
@renzon can you fit this issue into your schedule?

**Comment by elyezer** [comment]
>  ensure it is read again from server

I am not sure about the eq doing a request. In my opinion the equal should just serialize and compare. The eq can be used by users in order to identify if the entity needs to be updated. The fact that an entity returns a new object is to avoid changing the current object, there's more on the related issues and commits but I can't remember from the top of my head.

**Comment by renzon** [comment]
@omaciel sure. But just like @elyezer pointed out, it sound a "bad smell" to me __eq__ making requests. So code `if obj1==obj2` could fail because of network issues. Could you guys provide the use case for this feature? This way maybe we can come up with a better solution.

**Comment by rochacbruno** [comment]
@renzon agreed! That part is up to the user.

the use case is explained in Robotello 3984 https://github.com/SatelliteQE/robottelo/issues/3984

**Comment by renzon** [comment]
Ok, going to implement __eq__ by just serialization as json_dict and comparing.
