### ISSUE TITLE
in my test host does not have "build_status_label" key

### ISSUE THREAD

**Issue by jhutar** [SatelliteQE/nailgun#617]
In commit ebaf59ebe213ec1a9755078894317357ef90da91, field `build_status_label` was added to the Host entity, but I do not see it present in my hosts:

```
$ curl --silent --insecure -u admin:... -X GET -H 'Accept: application/json' https://satellite.nodhcp.local/api/v2/hosts/37 | json_reformat | grep -e managed -e build
    "build": false,
    "managed": false,
        "build"
    "provision_method": "build",
            "managed": true,
        "build_hosts": true,
```

Even with `...?show_hidden_parameters=1` it is not shown.

Any idea on why it is not showing?

Mine test is failing because of this:

```
$ pytest tests/foreman/api/test_host.py::HostTestCase::test_positive_update_managed_parameter --no-print-logs --capture=no --exitfirst 2>&1 | tee /tmp/pytest.log
[...]
>               setattr(entity, field_name, attrs[field_name])
E               KeyError: 'build_status_label'

venv/lib/python3.6/site-packages/nailgun/entity_mixins.py:822: KeyError
========================== 1 failed in 48.23 seconds ===========================
```

**Comment by jhutar** [comment]
Surprisingly only one test is failing with this error message :-O so I must be missing something. Is there some trigger which makes the field to appear?

**Comment by ntkathole** [comment]
@jhutar I see number of test failing due to this issue. Seems regression from PR #615 

- tests.foreman.ui_airgun.test_contenthost.test_positive_check_ignore_facts_os_setting
- tests.foreman.ui_airgun.test_errata.test_positive_filtered_errata_status_installable_param
- tests.foreman.ui_airgun.test_errata.test_positive_content_host_previous_env
-  tests.foreman.ui_airgun.test_errata.test_positive_filter_by_environment
-  tests.foreman.api.test_errata.ErrataTestCase.test_positive_get_applicable_for_host
-  tests.foreman.api.test_contentaccess.ContentAccessTestCase.test_positive_list_hosts_applicable
- tests.foreman.ui_airgun.test_hostcollection.*
-

**Comment by jhutar** [comment]
Oh, when I flipped unmanaged host to managed, I got the field. But I have managed hosts which do not have that field. What would be best way to proceed here?

**Comment by sean797** [comment]
@jhutar check production.log, I think it should give a error log

**Comment by rplevka** [comment]
@jhutar thanks for reporting this. Looks like we should add a conditional that would only fetch the build_status_label in case the host is managed.

**Comment by pgagne** [comment]
@jhutar any updates on this?
