### ISSUE TITLE
Remove `blinker_herald` dependency 

### ISSUE THREAD

**Issue by sean797** [SatelliteQE/nailgun#621]
I wanted to start a discussion around removing the `blinker_herald`.. 

I would like to remove `blinker_herald` as a dependency for Nailgun, as part of my work for with foreman-ansible-modules we would like to start packaging Nailgun as an RPM.

It would be easier to package without `blinker_herald` as if Nailgun, as it currently does, depends on it, I would have to package that first. So I ask, are we open to removing this dependency? If so, what would be the least painful approach to take?

Looking forward to a productive discussion. Thanks!

**Comment by sghai** [comment]
@san7ket @jyejare @mirzal @jhutar : Thoughts ?

**Comment by san7ket** [comment]
Hey sean, can we setup a call, to discuss this, hopefully will help in quick resolution.

**Comment by sean797** [comment]
@san7ket Sure, that would be good, please send me an invite :+1: sokeeffe@redhat.com

**Comment by JacobCallahan** [comment]
One option would be to incorporate it into nailgun, instead of trying to duplicate the functionality.
It is a pretty compact project, so that might not be difficult. 
@rochacbruno what do you think?

**Comment by san7ket** [comment]
@JacobCallahan yes, I was earlier testing the same, but the project has dependency on blinker. I am a POC ready, will raise it. Also, was planning to setup a call tomorrow, will invite you aswell.

**Comment by rochacbruno** [comment]
@JacobCallahan @san7ket 

Blinker was introduced ~2 years ago when we tried to have an active cleanup in robottelo, 
the idea was to use signals to detect every time an entity is created and then put in a list to be removed after tests.

After some tests we discovered that because of many issues we are not able to fully perform a cleanup of satellite entities, so we disabled the cleanup.

Looks like that cleanup are not in use, the cleanup is by default [disabled](https://github.com/SatelliteQE/robottelo/search?q=EntitiesCleaner&unscoped_q=EntitiesCleaner) 

So instead of vendoring `blinker_herald` I recommend the complete removal of it from nailgun.

1) Ensure that no one is using `nailgun.signals`
2) Remove this module entirely and all the `@emit` and other uses of blinker_herald

As a plus it will remove the signals overhead (a little, must be imperceptible but there are)

**Comment by JacobCallahan** [comment]
@rochacbruno Thanks for the clarification. I'm good with the removal, as this simplifies things even more.

**Comment by san7ket** [comment]
@rochacbruno Thanks, I will look into the removal and cleanup

**Comment by san7ket** [comment]
This need extensive removal and cleanup from robottelo as well and testing. Will continue this next week as well
