### ISSUE TITLE
Need to update new API's PATH for report templates, candlepin dynflow, host module streams, trend module stream in test_api_endtoend.py file.

### ISSUE THREAD

**Issue by devendra104** [SatelliteQE/nailgun#632]
Description: To update new API's PATH for report templates, candlepin dynflow, host module streams, trend module stream in existing test_api_endtoend.py file.
Reason: test_api_endtoend.py failed because of unavailable API path.
Output:
AssertionError: Items in the first set but not the second: 'report_templates' 'candlepin_dynflow_proxy' 'host_module_streams' 'trends' 'module_streams'

**Comment by mirzal** [comment]
You mean Robottelo's [tests/foreman/endtoend/test_api_endtoend.py](https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/endtoend/test_api_endtoend.py), right? Because there is no `test_api_endtoend.py` file in Nailgun.

When did it first fail? Seems this test hasn't been working for some time already, has it?

**Comment by devendra104** [comment]
Right the problem in  tests/foreman/endtoend/test_api_endtoend.py file.
Agreed, this is not related to Nailgun so I am closing this issue and will create a new issue in Robottelo's.

It failed during upgraded-6.5-end-to-end-rhel7 test case execution at "2019-05-07 05:59:46 ".
