### ISSUE TITLE
Content view filter creation errored

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/nailgun#92]
Issue:
```python
>>> cvf = ContentViewFilter(content_view=cv,type='erratum',name='filter1').create(True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/../virt_env/virt1/lib/python2.7/site-packages/nailgun/entity_mixins.py", line 719, in create
    return self.read(attrs=self.create_json(create_missing))
  File "/../virt_env/virt1/lib/python2.7/site-packages/nailgun/entities.py", line 924, in read
    return super(ContentViewFilter, self).read(entity, attrs, ignore)
  File "/../virt_env/virt1/lib/python2.7/site-packages/nailgun/entity_mixins.py", line 562, in read
    setattr(entity, field_name, attrs[field_name])
KeyError: 'original_packages'
```

Possible required fixes:
* original_packages is required only for package type filters. So may be 
'original_packages': entity_fields.BooleanField(null=True)?
* add logic to handle the fact that, this field is required only for package type filters.
* update the 'type' field to handle the choices (rpm, package_group, erratum)
* we need the logic to handle each 'type' assuming that different fields are used for different types

**Comment by Ichimonji10** [comment]
This error occurred because NailGun was expecting the server to return a value for the `original_packages` field but none was returned.

> original_packages is required only for package type filters. So may be 'original_packages': entity_fields.BooleanField(null=True)?

The `null` attribute indicates that `None` can be submitted as a value for that field. `null` isn't even used much, and it's only represented in NailGun b/c the API docs make so many mentions of it. It might be good to drop `null` entirely. The point is, `null=True` won't help us here.

@sthirugn, you mention that there are different types of content view filters. That's a promising lead. We've dealt with a similar situation with the `AbstractComputeResource` and its subclasses, `LibvirtComputeResource` and `DockerComputeResource`. The approach taken there may work well here too.
